name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test  --enable-code-coverage
      - name: Upload
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_SHUWANG1_LIBGNSS_CODES_TOKEN }}
